### ISSUE TITLE
Deploy my whole infrastructure

### ISSUE THREAD

**Issue by nzthiago** [rafaelmagu/chef-cabot#2]
I've been trying to deploy my solution with 200 VMs that could be done by an existing PaaS solution because I like to feel pain. Here's what I've tried:

```
sudo this sudo that
```

But it always fails with `this: command not found`

Help!

**Comment by rafaelmagu** [comment]
That will happen if you don't have the Microsoft Plus package for your operating system. Talk to your uncle Bill.
